# Generated by Django 3.2.2 on 2021-05-19 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата принятия в работу')),
                ('type', models.CharField(choices=[('COUNTERPARTY', 'В адрес контрагента'), ('SELF', 'В адрес Компании')], max_length=100, verbose_name='Тип претензии')),
                ('counterparty', models.CharField(max_length=200, verbose_name='Контрагент')),
                ('adress', models.CharField(blank=True, max_length=200, verbose_name='Адрес')),
                ('description', models.TextField(verbose_name='Описание')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('result', models.CharField(default='В работе', max_length=200, verbose_name='Результат')),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата поступления')),
                ('inspection_type', models.CharField(choices=[('RPN', 'Роспотребнадзор'), ('POLICE', 'Полиция'), ('PROSECUTOR', 'Прокуратура'), ('LABORE', 'ГИТ'), ('ATI', 'Ати/Администрация'), ('OTHERS', 'Иные контролирующие органы')], max_length=100, verbose_name='Тип проверки')),
                ('inspector', models.CharField(max_length=150, verbose_name='Проверяющий орган')),
                ('adress', models.CharField(blank=True, max_length=200, verbose_name='Адрес')),
                ('description', models.TextField(verbose_name='Описание')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('event', models.TextField(blank=True, verbose_name='Собития в рамках проверки')),
                ('result', models.CharField(default='В работе', max_length=200, verbose_name='Результат')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100, unique=True, verbose_name='Регион')),
            ],
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_date', models.DateField(verbose_name='Дата принятия принятия к производству')),
                ('court', models.CharField(max_length=300, verbose_name='Наименования судов')),
                ('case_number', models.CharField(max_length=200, verbose_name='Номер дела')),
                ('plaintiff', models.CharField(max_length=200, verbose_name='Истец')),
                ('defendant', models.CharField(max_length=200, verbose_name='Ответчик')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='Сумма требования')),
                ('subject', models.TextField(verbose_name='Предмет иска')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарии')),
                ('posible_result', models.IntegerField(verbose_name='Вероятность удовлетворения требований истка, %')),
                ('result', models.CharField(default='Рассматривается', max_length=300, verbose_name='Результат')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trials', to='tasks.region', verbose_name='Регион')),
            ],
        ),
    ]
