# Generated by Django 3.2.2 on 2021-05-19 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trials', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='tasks.region', verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='inspecions', to=settings.AUTH_USER_MODEL, verbose_name='Ответсвенный'),
        ),
        migrations.AddField(
            model_name='claim',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='tasks.region', verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='claim',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='claims', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
    ]
