# Generated by Django 3.2.2 on 2021-05-14 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_claims_claim'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Claim',
        ),
    ]
