# Generated by Django 3.2.2 on 2021-05-15 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0005_claim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_date', models.DateField(verbose_name='Дата принятия принятия к производству')),
                ('court', models.CharField(max_length=300, verbose_name='Наименования судов')),
                ('case_number', models.CharField(max_length=200, verbose_name='Номер дела')),
                ('plaintiff', models.CharField(max_length=200, verbose_name='Истец')),
                ('defendant', models.CharField(max_length=200, verbose_name='Ответчик')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='Сумма требования')),
                ('subject', models.TextField(verbose_name='Предмет иска')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарии')),
                ('posible_result', models.IntegerField(max_length=3, verbose_name='Вероятность удовлетворения требований истка, %')),
                ('result', models.CharField(default='Рассматривается', max_length=300, verbose_name='Результат')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trials', to='tasks.region', verbose_name='Регион')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trials', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
            ],
        ),
    ]
