# Generated by Django 3.2.2 on 2021-05-19 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_trial_posible_result'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspection',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='inspection',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='tasks.region', verbose_name='Регион'),
        ),
    ]
